use PCD_Database;
insert into Campaign values(1, NULL, NULL, NULL);
insert into Campaign values(0, NULL, NULL, NULL);
insert into Campaign values(110, NULL, NULL, 'I Like Ike');
insert into Campaign values(111, NULL, NULL, NULL);
insert into Campaign values(123, 61400000, NULL, NULL);
insert into Campaign values(122, 30000000, NULL, NULL);
insert into Campaign values(92, NULL, NULL, 'Return to Normalcy - Cox and Cocktails');
insert into Campaign values(91, NULL, NULL, NULL);
insert into Campaign values(129, 57700000, NULL, 'Are you better off than you were four years ago?');
insert into Campaign values(127, 49000000, NULL, NULL);
insert into Campaign values(126, NULL, NULL, NULL);
insert into Campaign values(128, NULL, NULL, NULL);
insert into Campaign values(93, NULL, NULL, 'Keep Cool With Coolidge');
insert into Campaign values(95, NULL, NULL, NULL);
insert into Campaign values(94, NULL, NULL, NULL);
insert into Campaign values(51, NULL, NULL, NULL);
insert into Campaign values(49, NULL, NULL, 'Free Soil, Free Labor, Free Speech, Free Men, and Fremont');
insert into Campaign values(50, NULL, NULL, NULL);
insert into Campaign values(84, NULL, NULL, NULL);
insert into Campaign values(83, NULL, NULL, NULL);
insert into Campaign values(59, NULL, NULL, NULL);
insert into Campaign values(58, NULL, NULL, NULL);
insert into Campaign values(96, NULL, NULL, 'A Chicken in Every Pot and a Car in Every Garage');
insert into Campaign values(97, NULL, NULL, NULL);
insert into Campaign values(78, NULL, NULL, 'Patriotism, Protection, and Prosperity - Good Money Never Made Times Hard');
insert into Campaign values(77, NULL, NULL, NULL);
insert into Campaign values(42, NULL, NULL, '54-40 or Fight - Reannexation of Texas and Reoccupation of Oregon');
insert into Campaign values(41, NULL, NULL, 'Who is James K. Polk?');
insert into Campaign values(81, NULL, NULL, NULL);
insert into Campaign values(82, NULL, NULL, NULL);
insert into Campaign values(74, NULL, NULL, NULL);
insert into Campaign values(76, NULL, NULL, NULL);
insert into Campaign values(75, NULL, NULL, NULL);
insert into Campaign values(31, NULL, NULL, NULL);
insert into Campaign values(30, NULL, NULL, NULL);
insert into Campaign values(33, NULL, NULL, NULL);
insert into Campaign values(32, NULL, NULL, NULL);
insert into Campaign values(21, NULL, NULL, NULL);
insert into Campaign values(20, NULL, NULL, NULL);
insert into Campaign values(137, 115400000, NULL, 'Building a Bridge to the 21st Century');
insert into Campaign values(139, 66800000, NULL, 'The Better Man for a Better America');
insert into Campaign values(138, NULL, NULL, NULL);
insert into Campaign values(38, NULL, NULL, NULL);
insert into Campaign values(34, NULL, NULL, NULL);
insert into Campaign values(36, NULL, NULL, NULL);
insert into Campaign values(37, NULL, NULL, NULL);
insert into Campaign values(35, NULL, NULL, NULL);
insert into Campaign values(19, NULL, NULL, NULL);
insert into Campaign values(18, NULL, NULL, NULL);
insert into Campaign values(132, 80000000, NULL, 'Kinder, Gentler Nation');
insert into Campaign values(133, 77300000, NULL, NULL);
insert into Campaign values(118, 8800000, NULL, 'The Stakes are too High for You to Stay at Home');
insert into Campaign values(117, 16000000, NULL, 'In your Heart you Know hes Right');
insert into Campaign values(102, NULL, NULL, NULL);
insert into Campaign values(103, NULL, NULL, NULL);
insert into Campaign values(134, 107900000, NULL, 'Dont stop thinking about tomorrow - Putting People First');
insert into Campaign values(135, 97400000, NULL, NULL);
insert into Campaign values(136, NULL, NULL, 'Ross for Boss');
insert into Campaign values(115, 9800000, NULL, NULL);
insert into Campaign values(116, 10100000, NULL, 'For the Future');
insert into Campaign values(114, NULL, NULL, NULL);
insert into Campaign values(104, NULL, NULL, NULL);
insert into Campaign values(105, NULL, NULL, NULL);
insert into Campaign values(80, NULL, NULL, 'A Full Dinner Pail');
insert into Campaign values(79, NULL, NULL, NULL);
insert into Campaign values(151, NULL, 328400000, 'Make America Great Again');
insert into Campaign values(150, NULL, 563900000, 'm With Her - Stronger Together');
insert into Campaign values(152, NULL, NULL, NULL);
insert into Campaign values(154, NULL, NULL, NULL);
insert into Campaign values(153, NULL, NULL, NULL);
insert into Campaign values(149, 737100000, 722400000, 'Forward');
insert into Campaign values(147, 483100000, 449900000, 'Believe in America');
insert into Campaign values(148, NULL, NULL, NULL);
insert into Campaign values(90, NULL, NULL, 'He Kept Us Out Of War');
insert into Campaign values(89, NULL, NULL, NULL);
insert into Campaign values(106, NULL, NULL, NULL);
insert into Campaign values(108, NULL, NULL, NULL);
insert into Campaign values(109, NULL, NULL, NULL);
insert into Campaign values(107, NULL, NULL, NULL);
insert into Campaign values(4, NULL, NULL, NULL);
insert into Campaign values(3, NULL, NULL, NULL);
insert into Campaign values(2, NULL, NULL, NULL);
insert into Campaign values(87, NULL, NULL, NULL);
insert into Campaign values(85, NULL, NULL, NULL);
insert into Campaign values(88, NULL, NULL, NULL);
insert into Campaign values(86, NULL, NULL, NULL);
insert into Campaign values(5, NULL, NULL, NULL);
insert into Campaign values(6, NULL, NULL, NULL);
insert into Campaign values(8, NULL, NULL, NULL);
insert into Campaign values(7, NULL, NULL, NULL);
insert into Campaign values(54, NULL, NULL, 'Vote Yourself a Farm');
insert into Campaign values(53, NULL, NULL, NULL);
insert into Campaign values(55, NULL, NULL, NULL);
insert into Campaign values(52, NULL, NULL, NULL);
insert into Campaign values(43, NULL, NULL, 'For President of the People');
insert into Campaign values(45, NULL, NULL, NULL);
insert into Campaign values(44, NULL, NULL, NULL);
insert into Campaign values(100, NULL, NULL, NULL);
insert into Campaign values(101, NULL, NULL, NULL);
insert into Campaign values(73, NULL, NULL, 'Rejuvenated Republicanism');
insert into Campaign values(72, NULL, NULL, NULL);
insert into Campaign values(121, 25400000, NULL, 'Nixos the One');
insert into Campaign values(120, 11600000, NULL, NULL);
insert into Campaign values(119, NULL, NULL, NULL);
insert into Campaign values(70, NULL, NULL, 'Blaine, Blaine, James G. Blaine, The Continental Liar from the State of Maine');
insert into Campaign values(71, NULL, NULL, 'Ma, Ma, Wheres my Pa, Gone to the White House, Ha, Ha, Ha');
insert into Campaign values(146, 760400000, 747800000, 'Change We Can Believe In - Change We Need - Hope - Yes We Can!');
insert into Campaign values(145, 239700000, 351500000, 'Country First');
insert into Campaign values(69, NULL, NULL, NULL);
insert into Campaign values(68, NULL, NULL, NULL);
insert into Campaign values(67, NULL, NULL, NULL);
insert into Campaign values(66, NULL, NULL, NULL);
insert into Campaign values(14, NULL, NULL, NULL);
insert into Campaign values(13, NULL, NULL, NULL);
insert into Campaign values(28, NULL, NULL, NULL);
insert into Campaign values(29, NULL, NULL, NULL);
insert into Campaign values(11, NULL, NULL, NULL);
insert into Campaign values(12, NULL, NULL, NULL);
insert into Campaign values(10, NULL, NULL, NULL);
insert into Campaign values(9, NULL, NULL, NULL);
insert into Campaign values(26, NULL, NULL, NULL);
insert into Campaign values(27, NULL, NULL, NULL);
insert into Campaign values(25, NULL, NULL, NULL);
insert into Campaign values(24, NULL, NULL, NULL);
insert into Campaign values(39, NULL, NULL, 'Tippecanoe and Tyler Too');
insert into Campaign values(40, NULL, NULL, NULL);
insert into Campaign values(22, NULL, NULL, NULL);
insert into Campaign values(23, NULL, NULL, NULL);
insert into Campaign values(17, NULL, NULL, NULL);
insert into Campaign values(15, NULL, NULL, NULL);
insert into Campaign values(16, NULL, NULL, NULL);
insert into Campaign values(142, 186500000, NULL, 'Compassionate Conservatism - Leave no Child Behind - Real Plans for Real People - Reformer With Results');
insert into Campaign values(141, 120300000, NULL, 'Prosperity and Progress - Prosperity for Americs Families');
insert into Campaign values(140, NULL, NULL, 'Government Of, By, and For the People...Not the Monied Interests');
insert into Campaign values(112, NULL, NULL, 'Peace and Prosperity');
insert into Campaign values(113, NULL, NULL, NULL);
insert into Campaign values(144, 355000000, NULL, 'Yes, America Can!');
insert into Campaign values(143, 332700000, NULL, 'Let America be America Again');
insert into Campaign values(124, 33400000, NULL, 'Not Just Peanuts - A Leader, For a Change');
insert into Campaign values(125, 35800000, NULL, 'Hes Making us Proud Again');
insert into Campaign values(61, NULL, NULL, NULL);
insert into Campaign values(64, NULL, NULL, NULL);
insert into Campaign values(63, NULL, NULL, NULL);
insert into Campaign values(65, NULL, NULL, NULL);
insert into Campaign values(60, NULL, NULL, NULL);
insert into Campaign values(62, NULL, NULL, NULL);
insert into Campaign values(98, NULL, NULL, NULL);
insert into Campaign values(99, NULL, NULL, NULL);
insert into Campaign values(131, 67500000, NULL, 'Its Morning Again in America');
insert into Campaign values(130, 66700000, NULL, 'America Needs a Change');
insert into Campaign values(46, NULL, NULL, NULL);
insert into Campaign values(47, NULL, NULL, NULL);
insert into Campaign values(48, NULL, NULL, NULL);
insert into Campaign values(56, NULL, NULL, 'Dot Swap Horses in the Middle of the Stream');
insert into Campaign values(57, NULL, NULL, NULL);
