use PCD_Database;insert into Party values(0, 'Reform');
insert into Party values(1, 'Various');
insert into Party values(2, 'Independent');
insert into Party values(3, 'Constitutional Union');
insert into Party values(4, 'Free Soil');
insert into Party values(5, 'Republican');
insert into Party values(6, 'Anti-Masonic');
insert into Party values(7, 'Democratic-Republican');
insert into Party values(8, 'Federalist');
insert into Party values(9, 'Progressive');
insert into Party values(10, 'Democrat-Populist');
insert into Party values(11, 'Socialist');
insert into Party values(12, 'American');
insert into Party values(13, 'Green');
insert into Party values(14, 'Democratic');
insert into Party values(15, 'National Republican');
insert into Party values(16, 'Anti-Federalist');
insert into Party values(17, 'Whig');
insert into Party values(18, 'State Rights Democratic');
insert into Party values(19, 'Peopls');
insert into Party values(20, 'American Independent');
insert into Party values(21, 'Libertarian');
