use PCD_Database;
insert into Nominee values(0, 'Hillary R. Clinton');
insert into Nominee values(1, 'Calvin Coolidge');
insert into Nominee values(2, 'Rufus King');
insert into Nominee values(3, 'Wendell L. Willkie');
insert into Nominee values(4, 'James M. Cox');
insert into Nominee values(5, 'Ed Clark');
insert into Nominee values(6, 'Gary Johnson');
insert into Nominee values(7, 'Gerald R. Ford');
insert into Nominee values(8, 'Thomas Jefferson');
insert into Nominee values(9, 'John P. Hale');
insert into Nominee values(10, 'Charles C. Pinckney');
insert into Nominee values(11, 'Walter F. Mondale');
insert into Nominee values(12, 'Horatio Seymour');
insert into Nominee values(13, 'De Witt Clinton');
insert into Nominee values(14, 'Harry F. Byrd');
insert into Nominee values(15, 'Jimmy Carter');
insert into Nominee values(16, 'William J. Clinton');
insert into Nominee values(17, 'Franklin Pierce');
insert into Nominee values(18, 'Hubert H. Humphrey');
insert into Nominee values(19, 'Barry M. Goldwater');
insert into Nominee values(20, 'George Clinton');
insert into Nominee values(21, 'Grover Cleveland');
insert into Nominee values(22, 'William H. Harrison');
insert into Nominee values(23, 'Ulysses S. Grant');
insert into Nominee values(24, 'W. Mitt Romney');
insert into Nominee values(25, 'Theodore Roosevelt');
insert into Nominee values(26, 'William J. Bryan');
insert into Nominee values(27, 'Harry S. Truman');
insert into Nominee values(28, 'James B. Weaver');
insert into Nominee values(29, 'Eugene Debs');
insert into Nominee values(30, 'Henry Wallace');
insert into Nominee values(31, 'Donald J. Trump');
insert into Nominee values(32, 'Henry Clay');
insert into Nominee values(33, 'John C. Breckinridge');
insert into Nominee values(34, 'William H. Crawford');
insert into Nominee values(35, 'Abraham Lincoln');
insert into Nominee values(36, 'Dwight D. Eisenhower');
insert into Nominee values(37, 'John Adams');
insert into Nominee values(38, 'Alton B. Parker');
insert into Nominee values(39, 'Samuel J. Tilden');
insert into Nominee values(40, 'Thomas E. Dewey');
insert into Nominee values(41, 'Robert M. LaFollette');
insert into Nominee values(42, 'W.P. Mangum');
insert into Nominee values(43, 'John C. Fremont');
insert into Nominee values(44, 'Herbert C. Hoover');
insert into Nominee values(45, 'Hugh L. White');
insert into Nominee values(46, 'William McKinley');
insert into Nominee values(47, 'Adlai Stevenson');
insert into Nominee values(48, 'John F. Kerry');
insert into Nominee values(49, 'Andrew Jackson');
insert into Nominee values(50, 'Millard Fillmore');
insert into Nominee values(51, 'James Monroe');
insert into Nominee values(52, 'Zachary Taylor');
insert into Nominee values(53, 'Warren G. Harding');
insert into Nominee values(54, 'James A. Garfield');
insert into Nominee values(55, 'George Washington');
insert into Nominee values(56, 'Horace Greeley');
insert into Nominee values(57, 'George Bush');
insert into Nominee values(58, 'Ralph Nader');
insert into Nominee values(59, 'Benjamin Harrison');
insert into Nominee values(60, 'John Quincy Adams');
insert into Nominee values(61, 'Rutherford B. Hayes');
insert into Nominee values(62, 'James G. Blaine');
insert into Nominee values(63, 'James Buchanan');
insert into Nominee values(64, 'Albert Gore');
insert into Nominee values(65, 'Alfred E. Smith');
insert into Nominee values(66, 'B. Gratz Brown');
insert into Nominee values(67, 'Winfield Scott');
insert into Nominee values(68, 'John S. McCain');
insert into Nominee values(69, 'Lyndon B. Johnson');
insert into Nominee values(70, 'Evan McMullin');
insert into Nominee values(71, 'Charles E. Hughes');
insert into Nominee values(72, 'Woodrow Wilson');
insert into Nominee values(73, 'Daniel Webster');
insert into Nominee values(74, 'Barack H. Obama');
insert into Nominee values(75, 'George W. Bush');
insert into Nominee values(76, 'William H. Taft');
insert into Nominee values(77, 'George B. McClellan');
insert into Nominee values(78, 'Martin Van Buren');
insert into Nominee values(79, 'Thomas A. Hendricks');
insert into Nominee values(80, 'William Wirt');
insert into Nominee values(81, 'Aaron Burr');
insert into Nominee values(82, 'J. Strom Thurmond');
insert into Nominee values(83, 'Ross Perot');
insert into Nominee values(84, 'James Madison');
insert into Nominee values(85, 'Ronald Reagan');
insert into Nominee values(86, 'John Bell');
insert into Nominee values(87, 'Lewis Cass');
insert into Nominee values(88, 'Robert Dole');
insert into Nominee values(89, 'John W. Davis');
insert into Nominee values(90, 'John Floyd');
insert into Nominee values(91, 'John F. Kennedy');
insert into Nominee values(92, 'Charles J. Jenkins');
insert into Nominee values(93, 'Alfred M. Landon');
insert into Nominee values(94, 'Jill Stein');
insert into Nominee values(95, 'George McGovern');
insert into Nominee values(96, 'Richard M. Nixon');
insert into Nominee values(97, 'James K. Polk');
insert into Nominee values(98, 'Thomas Pinckney');
insert into Nominee values(99, 'Michael S. Dukakis');
insert into Nominee values(100, 'Franklin D. Roosevelt');
insert into Nominee values(101, 'John Anderson');
insert into Nominee values(102, 'Winfield S. Hancock');
insert into Nominee values(103, 'David Davis');
insert into Nominee values(104, 'Stephen A. Douglas');
insert into Nominee values(105, 'George C. Wallace');
