use PCD_Database;
insert into Vice values(110, 'Richard Nixon');
insert into Vice values(111, 'John Sparkman');
insert into Vice values(123, 'Spiro Agnew');
insert into Vice values(122, 'Sargent Shriver');
insert into Vice values(92, 'Calvin Coolidge');
insert into Vice values(91, 'Franklin Roosevelt');
insert into Vice values(129, 'George H. W. Bush');
insert into Vice values(127, 'Walter Mondale');
insert into Vice values(93, 'Charles G. Dawes');
insert into Vice values(95, 'Charles W. Bryan');
insert into Vice values(51, 'John C. Breckinridge');
insert into Vice values(49, 'William Dayton');
insert into Vice values(84, 'James S. Sherman');
insert into Vice values(83, 'John W. Kern');
insert into Vice values(59, 'Schuyler Colfax');
insert into Vice values(58, 'Francis Blair');
insert into Vice values(96, 'Charles Curtis');
insert into Vice values(97, 'Joseph Taylor Robinson');
insert into Vice values(78, 'Garret Hobart');
insert into Vice values(77, 'Arthur Sewall');
insert into Vice values(81, 'Charles W. Fairbanks');
insert into Vice values(82, 'Henry G. Davis');
insert into Vice values(74, 'Adlai E. Stevenson');
insert into Vice values(76, 'Whitelaw Reid');
insert into Vice values(137, 'Al Gore');
insert into Vice values(139, 'Jack Kemp');
insert into Vice values(132, 'Dan Quayle');
insert into Vice values(133, 'Lloyd Bentsen');
insert into Vice values(118, 'Hubert Humphrey');
insert into Vice values(117, 'William E. Miller');
insert into Vice values(102, 'Henry A. Wallace');
insert into Vice values(103, 'Charles L. McNary');
insert into Vice values(134, 'Al Gore');
insert into Vice values(135, 'Dan Quayle');
insert into Vice values(115, 'Lyndon B. Johnson');
insert into Vice values(116, 'Henry Cabot Lodge Jr.');
insert into Vice values(104, 'Harry S. Truman');
insert into Vice values(105, 'John W. Bricker');
insert into Vice values(80, 'Theodore Roosevelt');
insert into Vice values(79, 'Adlai E. Stevenson');
insert into Vice values(151, 'Mike Pence');
insert into Vice values(150, 'Tim Kaine');
insert into Vice values(149, 'Joe Biden');
insert into Vice values(147, 'Paul Ryan');
insert into Vice values(90, 'Thomas R. Marshall');
insert into Vice values(89, 'Charles W. Fairbanks');
insert into Vice values(106, 'Alben W. Barkley');
insert into Vice values(108, 'Earl Warren');
insert into Vice values(87, 'Thomas R. Marshall');
insert into Vice values(88, 'Nicholas M. Butler');
insert into Vice values(54, 'Hannibal Hamlin');
insert into Vice values(52, 'Herschel Vespasian Johnson');
insert into Vice values(100, 'John Nance Garner');
insert into Vice values(101, 'Frank Knox');
insert into Vice values(73, 'Levi Morton');
insert into Vice values(72, 'Allen G. Thurman');
insert into Vice values(121, 'Spiro Agnew');
insert into Vice values(120, 'Edmund Muskie');
insert into Vice values(70, 'Thomas Hendricks');
insert into Vice values(71, 'John A. Logan');
insert into Vice values(146, 'Joe Biden');
insert into Vice values(145, 'Sarah Palin');
insert into Vice values(69, 'Chester A. Arthur');
insert into Vice values(68, 'William English');
insert into Vice values(67, 'William A. Wheeler');
insert into Vice values(66, 'Thomas Hendricks');
insert into Vice values(142, 'Dick Cheney');
insert into Vice values(141, 'Joe Lieberman');
insert into Vice values(112, 'Richard Nixon');
insert into Vice values(113, 'Estes Kefauver');
insert into Vice values(144, 'Dick Cheney');
insert into Vice values(143, 'John Edwards');
insert into Vice values(124, 'Walter Mondale');
insert into Vice values(125, 'Bob Dole');
insert into Vice values(61, 'Henry Wilson');
insert into Vice values(62, 'B. Gratz Brown');
insert into Vice values(98, 'John Nance Garner');
insert into Vice values(99, 'Charles Curtis');
insert into Vice values(131, 'George H. W. Bush');
insert into Vice values(130, 'Geraldine Ferraro');
insert into Vice values(56, 'Andrew Johnson');
insert into Vice values(57, 'George Hunt Pendleton');
